"""Extract country calling codes from libphonenumber metadata.

Reads PhoneNumberMetadata.xml from libphonenumber and writes an Android
string-array resource with one "REGION:CODE" item per territory
(for example "FR:33"). Non-geographical entities (id "001") are skipped.

Usage:
    curl -L -o /tmp/PhoneNumberMetadata.xml \
      https://raw.githubusercontent.com/google/libphonenumber/master/resources/PhoneNumberMetadata.xml
    python3 tools/extract_country_codes.py /tmp/PhoneNumberMetadata.xml \
      app/src/main/res/values/country_codes.xml

The source data is licensed under the Apache License, Version 2.0.
"""

import sys
import xml.etree.ElementTree as ET

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Country calling codes extracted from libphonenumber
     (resources/PhoneNumberMetadata.xml), Copyright (C) 2009 The Libphonenumber Authors,
     licensed under the Apache License, Version 2.0.
     Modified: only the region id and countryCode attributes were extracted.
     Generated by tools/extract_country_codes.py. Do not edit by hand. -->
<resources>
    <string-array name="country_calling_codes" translatable="false">
"""
FOOTER = """    </string-array>
</resources>
"""

root = ET.parse(sys.argv[1]).getroot()
entries = [
    (t.get("id"), t.get("countryCode"))
    for t in root.iter("territory")
    if t.get("id") != "001"
]

with open(sys.argv[2], "w", encoding="utf-8") as out:
    out.write(HEADER)
    for region, code in entries:
        out.write(f"        <item>{region}:{code}</item>\n")
    out.write(FOOTER)
print(f"{len(entries)} entries written")
